CREATE TABLE teams (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL UNIQUE,
	acronym VARCHAR NOT NULL UNIQUE,
	budget BIGINT NOT NULL
);

CREATE TABLE players (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	position VARCHAR NOT NULL CHECK (position IN ('FORWARD', 'MIDFIELD', 'DEFENDER', 'GOALKEEPER')),
	team_id BIGINT NOT NULL REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX players_team_id ON players(id);
